config/routes.rb
Rails.application.routes.draw do
  devise_for :useres
  resources :administradores
  resources :enderecos
  resources :enderecoses
  resources :fornecedor_tipos
  resources :fornecedores do
    resources :fornecedores_enderecos
  end

  get '/bandeira', to: 'bandeira#index'
  
  get '/stimulus', to: 'stimulus#index'

  get '/login', to: 'login#index'
  delete '/users/sign_out', to: 'devise/sessions#destroy'
  post '/login', to: 'login#logar'

  root "home#index"

  get '/carros', to: 'carros#index', as: 'carros'
  get '/carros/novo', to: 'carros#novo', as: 'carros_novo'
  post '/carros', to: 'carros#criar', as: 'carros_criar'
  get '/carros/:id', to: 'carros#show', as: 'carros_show'
  put '/carros/:id', to: 'carros#alterar', as: 'carros_alterar'
  get '/carros/:id/editar', to: 'carros#editar', as: 'carros_editar'
  delete '/carros/:id', to: 'carros#apagar', as: 'carros_apagar'
end

app/models/carro.rb
class Carro < ApplicationRecord
    validates_presence_of :nome, :modelo, :ano
    validates_length_of :nome, minimum: 2, maximum: 100
    validates_numericality_of :ano, greater_than_or_equal_to: 2000
    validates_numericality_of :ano, less_than_or_equal_to: Time.now.year
    validates_numericality_of :ano, only_integer: true
    # validates_numericality_of :ano, odd: true # impar
    # validates_numericality_of :ano, even: true # par

    # validate :customizada

    # def customizada
    #     puts "=== entrou na validação ===="
    #     self.errors.add("erro", "erro")
    # end

    # after_validation :mostra_no_console
    # before_validation :mostra_no_console

    # before_create :mostra_no_console
    # after_create :mostra_no_console

    # before_update :mostra_no_console
    # after_update :mostra_no_console

    # before_save :mostra_no_console
    # after_save :mostra_no_console

    # before_destroy :mostra_no_console
    # after_save :mostra_no_console

    def mostra_no_console
        puts "=== Mostrando algo no before_destroy ===="
    end

    # after = depois
    # before = antes

    # validation
    # save
    # update
    # create
    # destroy


    def self.busca_carro_por_id(id)
        carro = Carro.find(id)
        # carro = Carro.where(id: id).first
        carro.nome = "#{carro.nome} - alterao pelo metodo busca_carro_por_id"
        carro
    end
end

app/controllers/carros_controller.rb
class CarrosController < ApplicationController
    layout 'logada'
    
    def index
        @carros = Carro.paginate(page: params[:page] || 1, per_page: 3)
    end

    def show
        @carro = Carro.find(params[:id])
    end

    def editar
        @carro = Carro.find(params[:id])
    end

    def novo
        @carro = Carro.new
    end

    def criar
        @carro = Carro.new(nome: params[:nome], modelo: params[:modelo], ano: params[:ano])

        if @carro.save
            flash[:success] = "Carro criado com sucesso"
            return redirect_to carros_path
        end

        render :novo, status: :unprocessable_entity
    end

    def alterar
        @carro = Carro.find(params[:id])
        @carro.nome = params[:nome]
        @carro.modelo = params[:modelo]
        @carro.ano = params[:ano]
        if @carro.save
            flash[:success] = "Carro atualizado com sucesso"
            return redirect_to carros_path
        end

        render :editar, status: :unprocessable_entity
    end

    def apagar
        carro = Carro.find(params[:id])
        carro.destroy

        flash[:success] = "Carro apagado com sucesso"

        redirect_to carros_path
    end
end

app/helpers/carros_helper.rb
module CarrosHelper
end

app/views/carros/_form.html.erb
<form action="<%= carro.new_record? ? carros_criar_path : carros_alterar_path(carro) %>" method="POST">

    <% if carro.errors.any? %>
        <div style="color: red">
            <h2>
            Contém <%= carro.errors.count %> erro(s) para ser resolvidos abaixo:
            </h2>

            <ul>
            <% carro.errors.each do |error| %>
                <li><%= error.full_message %></li>
            <% end %>
            </ul>
        </div>
    <% end %>

    <% unless carro.new_record? %>
        <input type="hidden" name="_method" value="put" />
    <% end %>
    
    <div><strong>Nome</strong>: <input type="text" value="<%= carro.nome %>" name="nome"> </div>
    <div><strong>Modelo</strong>: <input type="text" value="<%= carro.modelo %>" name="modelo"></div>
    <div><strong>Ano</strong>: <input type="text" value="<%= carro.ano %>" name="ano"></div>

    <hr>
    <button type="submit" class="btn btn-primary">Enviar</button>
    <a href="/carros" class="btn btn-warning">Voltar para a lista</a>
</form>

app/views/carros/editar.html.erb
<section class="text-center container">
    <h1>Mostrando o carro</h1>

    <hr>

    <div style="text-align:left">
        <%= render "form", carro: @carro %>
    </div>
</section>

app/views/carros/index.html.erb
<section class="text-center container">
    <h1>Lista de carros</h1>

    <%= render "/shared/h1_bem_vindo" %>

    <hr>
    <div style="text-align:right">
        <a href="<%= carros_novo_path %>" class="btn btn-primary">Novo</a>
    </div>
    <hr>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>Modelo</th>
                <th>Ano</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <% @carros.each do |carro| %>
                <tr>
                    <td><%= carro.id %></td>
                    <td><%= carro.nome %></td>
                    <td><%= carro.modelo %></td>
                    <td><%= carro.ano %></td>
                    <td style="width:260px">
                        <%= link_to "Mostrar", carros_show_path(carro.id), "class": "btn btn-primary" %>
                        <%= link_to "editar", carros_editar_path(carro.id), "class": "btn btn-warning" %>
                        <form style="display:inline" action="<%= carros_apagar_path(carro.id) %>" onsubmit="return confirm('Confirma?')" method="POST">
                            <input type="hidden" name="_method" value="delete" />
                            <button type="submit" class="btn btn-danger">Apagar</button>
                        </form>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>

    <div class="digg_pagination">
        <%= will_paginate(@carros, previous_label: '<<', next_label: '>>') %>
    </div>
<section>

app/views/carros/novo.html.erb
<section class="text-center container">
    <h1>Mostrando o carro</h1>

    <hr>

    <div style="text-align:left">
        <%= render "form", carro: @carro %>
    </div>
</section>

app/views/carros/show.html.erb
<section class="text-center container">
    <h1>Mostrando o carro</h1>

    <hr>

    <div style="text-align:left">
        <div><strong>Id</strong>: <%= @carro.id %></div>
        <div><strong>Nome</strong>: <%= @carro.nome %></div>
        <div><strong>Modelo</strong>: <%= @carro.modelo %></div>
        <div><strong>Ano</strong>: <%= @carro.ano %></div>
        <hr>
        <a href="/carros" class="btn btn-warning">Voltar para a lista</a>
    </div>
</section>