config/routes.rb
Rails.application.routes.draw do
  devise_for :useres
  resources :administradores
  resources :enderecos
  resources :enderecoses
  resources :fornecedor_tipos
  resources :fornecedores do
    resources :fornecedores_enderecos
  end

  get '/bandeira', to: 'bandeira#index'
  
  get '/stimulus', to: 'stimulus#index'

  get '/login', to: 'login#index'
  delete '/users/sign_out', to: 'devise/sessions#destroy'
  post '/login', to: 'login#logar'

  root "home#index"

  get '/carros', to: 'carros#index', as: 'carros'
  get '/carros/novo', to: 'carros#novo', as: 'carros_novo'
  post '/carros', to: 'carros#criar', as: 'carros_criar'
  get '/carros/:id', to: 'carros#show', as: 'carros_show'
  put '/carros/:id', to: 'carros#alterar', as: 'carros_alterar'
  get '/carros/:id/editar', to: 'carros#editar', as: 'carros_editar'
  delete '/carros/:id', to: 'carros#apagar', as: 'carros_apagar'
end

app/controllers/fornecedores_controller.rb
class FornecedoresController < ApplicationController
  before_action :set_fornecedor, only: %i[ show edit update destroy ]
  layout 'logada'

  # GET /fornecedores or /fornecedores.json
  def index
    @fornecedores = Fornecedor.all
  end

  # GET /fornecedores/1 or /fornecedores/1.json
  def show
  end

  # GET /fornecedores/new
  def new
    @fornecedor = Fornecedor.new
  end

  # GET /fornecedores/1/edit
  def edit
  end

  # POST /fornecedores or /fornecedores.json
  def create
    @fornecedor = Fornecedor.new(fornecedor_params)

    respond_to do |format|
      if @fornecedor.save
        format.html { redirect_to fornecedor_url(@fornecedor), notice: "Fornecedor criado com sucesso." }
        format.json { render :show, status: :created, location: @fornecedor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fornecedores/1 or /fornecedores/1.json
  def update
    respond_to do |format|
      if @fornecedor.update(fornecedor_params)
        format.html { redirect_to fornecedor_url(@fornecedor), notice: "Fornecedor foi atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @fornecedor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fornecedores/1 or /fornecedores/1.json
  def destroy
    @fornecedor.destroy!

    respond_to do |format|
      format.html { redirect_to fornecedores_url, notice: "Fornecedor foi apagado com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fornecedor
      @fornecedor = Fornecedor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fornecedor_params
      params.require(:fornecedor).permit(:nome, :cnpj, :endereco, :cep, :email, :senha, :confirmacao_senha, :termos_de_uso, :fornecedor_tipo_id)
    end
end

app/helpers/fornecedores_helper.rb
module FornecedoresHelper
    def formata_hora(data)
        return data.strftime("%d/%m/%Y %H:%M")
    end

    def somar_fornecedor(fornecedor)
        fornecedor.id + 100
    end
end

app/views/fornecedores/_form.html.erb
<%= form_with(model: fornecedor) do |form| %>
  <% if fornecedor.errors.any? %>
    <div style="color: red">
      <h2>
        Contém <%= fornecedor.errors.count %> erro(s) para ser resolvidos abaixo:
      </h2>

      <ul>
        <% fornecedor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :fornecedor_tipo_id, style: "display: block" %>
    <%= form.collection_select :fornecedor_tipo_id, FornecedorTipo.all, :id, :nome, { prompt: "Selecione um Tipo" }, { class: "form-control" } %>
  </div>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome, class: "form-control" %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div>
    <%= form.label :cnpj, style: "display: block" %>
    <%= form.text_field :cnpj, class: "form-control" %>
  </div>

  <div>
    <%= form.label :endereco, style: "display: block" %>
    <%= form.text_area :endereco, class: "form-control" %>
  </div>

  <div>
    <%= form.label :cep, style: "display: block" %>
    <%= form.text_field :cep, class: "form-control" %>
  </div>

  <div>
    <%= form.label :senha, style: "display: block" %>
    <%= form.password_field :senha, class: "form-control" %>
  </div>
  <div>
    <%= form.label :senha_confirmation, style: "display: block" %>
    <%= form.password_field :senha_confirmation, class: "form-control" %>
  </div>


  <div>
    <%= form.label :termos_de_uso, style: "display: block" %>
    <%= form.check_box :termos_de_uso %>
  </div>

  <br>
  <div>
    <%= form.submit "Salvar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/fornecedores/_fornecedor.html.erb
<div id="<%= dom_id fornecedor %>">

  <p>
    <strong>Tipo:</strong>
    <%= fornecedor.fornecedor_tipo&.nome %>
  </p>

  <p>
    <strong>Nome:</strong>
    <%= fornecedor.nome %>
  </p>

  <p>
    <strong>Cnpj:</strong>
    <%= fornecedor.cnpj %>
  </p>

  <p>
    <strong>Endereco:</strong>
    <%= fornecedor.endereco %>
  </p>

  <p>
    <strong>Data Criação:</strong>
    <%= formata_hora(fornecedor.created_at) %>
  </p>

  <p>
    <strong>Soma:</strong>
    <%= somar_fornecedor(fornecedor) %>
  </p>


  <p>
    <%= link_to "Cadastrar enderecos", fornecedor_fornecedores_enderecos_path(fornecedor) %>
  </p>

</div>

app/views/fornecedores/edit.html.erb
<h1>Editing fornecedor</h1>

<%= render "form", fornecedor: @fornecedor %>

<br>

<div>
  <%= link_to "Mostrar", @fornecedor, class: "btn btn-warning" %> |
  <%= link_to "Voltar", fornecedores_path %>
</div>

app/views/fornecedores/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Fornecedores</h1>

<%= render "/shared/h1_bem_vindo" %>

<div id="fornecedores">
  <% @fornecedores.each do |fornecedor| %>
    <%= render fornecedor %>
    <p>
      <%= link_to "Mostrar", fornecedor, class: "btn btn-warning" %>
    </p>
    <hr>
  <% end %>
</div>

<%= link_to "New fornecedor", new_fornecedor_path, class: "btn btn-primary" %>

app/views/fornecedores/new.html.erb
<h1>New fornecedor</h1>

<%= render "form", fornecedor: @fornecedor %>

<br>

<div>
  <%= link_to "Voltar", fornecedores_path %>
</div>

app/views/fornecedores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @fornecedor %>

<div>
  <%= link_to "Editar", edit_fornecedor_path(@fornecedor), class: "btn btn-warning" %> |
  <%= link_to "Voltar", fornecedores_path, class: "btn btn-default" %>

  <%= button_to "Apagar", @fornecedor, class: "btn btn-danger", method: :delete, form: { style: "display:inline", onsubmit: "return confirm('Tem certeza que deseja apagar?')" } %>
</div>