config/routes.rb
Rails.application.routes.draw do
  devise_for :useres
  resources :administradores
  resources :enderecos
  resources :enderecoses
  resources :fornecedor_tipos
  resources :fornecedores do
    resources :fornecedores_enderecos
  end

  get '/bandeira', to: 'bandeira#index'
  
  get '/stimulus', to: 'stimulus#index'

  get '/login', to: 'login#index'
  delete '/users/sign_out', to: 'devise/sessions#destroy'
  post '/login', to: 'login#logar'

  root "home#index"

  get '/carros', to: 'carros#index', as: 'carros'
  get '/carros/novo', to: 'carros#novo', as: 'carros_novo'
  post '/carros', to: 'carros#criar', as: 'carros_criar'
  get '/carros/:id', to: 'carros#show', as: 'carros_show'
  put '/carros/:id', to: 'carros#alterar', as: 'carros_alterar'
  get '/carros/:id/editar', to: 'carros#editar', as: 'carros_editar'
  delete '/carros/:id', to: 'carros#apagar', as: 'carros_apagar'
end

app/models/fornecedores_endereco.rb
class FornecedoresEndereco < ApplicationRecord
  belongs_to :endereco
  belongs_to :fornecedor

  validates_presence_of :endereco_id, :fornecedor_id
end

app/controllers/fornecedores_enderecos_controller.rb
class FornecedoresEnderecosController < ApplicationController
  layout 'logada'
  before_action :set_fornecedores_endereco, only: %i[ show edit update destroy ]
  before_action :set_fornecedor

  # GET /fornecedores_enderecos or /fornecedores_enderecos.json
  def index
    @fornecedores_enderecos = FornecedoresEndereco.where(fornecedor_id: @fornecedor.id)
  end

  # GET /fornecedores_enderecos/1 or /fornecedores_enderecos/1.json
  def show
  end

  # GET /fornecedores_enderecos/new
  def new
    @fornecedores_endereco = FornecedoresEndereco.new
  end

  # GET /fornecedores_enderecos/1/edit
  def edit
  end

  # POST /fornecedores_enderecos or /fornecedores_enderecos.json
  def create
    @fornecedores_endereco = FornecedoresEndereco.new(fornecedores_endereco_params)
    @fornecedores_endereco.fornecedor_id = @fornecedor.id

    respond_to do |format|
      if @fornecedores_endereco.save
        format.html { redirect_to fornecedor_fornecedores_endereco_url(@fornecedor, @fornecedores_endereco), notice: "Fornecedores endereco was successfully created." }
        format.json { render :show, status: :created, location: @fornecedores_endereco }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fornecedores_endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fornecedores_enderecos/1 or /fornecedores_enderecos/1.json
  def update
    respond_to do |format|
      if @fornecedores_endereco.update(fornecedores_endereco_params)
        format.html { redirect_to fornecedor_fornecedores_endereco_url(@fornecedor, @fornecedores_endereco), notice: "Fornecedores endereco was successfully updated." }
        format.json { render :show, status: :ok, location: @fornecedores_endereco }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fornecedores_endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fornecedores_enderecos/1 or /fornecedores_enderecos/1.json
  def destroy
    @fornecedores_endereco.destroy!

    respond_to do |format|
      format.html { redirect_to fornecedor_fornecedores_enderecos_url(@fornecedor), notice: "Fornecedores endereco was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fornecedores_endereco
      @fornecedores_endereco = FornecedoresEndereco.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fornecedores_endereco_params
      params.require(:fornecedores_endereco).permit(:endereco_id)
    end

    def set_fornecedor
      @fornecedor = Fornecedor.find(params[:fornecedor_id])
    end

    def depois_do_fornecedor
      # debugger
      x = ""
    end
end

app/helpers/fornecedores_enderecos_helper.rb
module FornecedoresEnderecosHelper
end

app/views/fornecedores_enderecos/_form.html.erb
<%= form_with(model: [@fornecedor, fornecedores_endereco]) do |form| %>
  <% if fornecedores_endereco.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(fornecedores_endereco.errors.count, "error") %> prohibited this fornecedores_endereco from being saved:</h2>

      <ul>
        <% fornecedores_endereco.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :endereco_id, style: "display: block" %>
    <%= form.collection_select :endereco_id, Endereco.all, :id, :logradouro, { prompt: "Selecione um endereço" }, { class: "form-control" } %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/fornecedores_enderecos/_fornecedores_endereco.html.erb
<div id="<%= dom_id fornecedores_endereco %>">
  <p>
    <strong>Logradouro:</strong>
    <%= fornecedores_endereco.endereco.logradouro %>
  </p>

  <p>
    <strong>Numero:</strong>
    <%= fornecedores_endereco.endereco.numero %>
  </p>

  <p>
    <strong>Cep:</strong>
    <%= fornecedores_endereco.endereco.cep %>
  </p>

  <p>
    <strong>Cidade:</strong>
    <%= fornecedores_endereco.endereco.cidade %>
  </p>

  <p>
    <strong>Estado:</strong>
    <%= fornecedores_endereco.endereco.estado %>
  </p>

  <p>
    <strong>Complemento:</strong>
    <%= fornecedores_endereco.endereco.complemento %>
  </p>

</div>

app/views/fornecedores_enderecos/edit.html.erb
<h1>Editing fornecedores endereco</h1>

<%= render "form", fornecedores_endereco: @fornecedores_endereco %>

<br>

<div>
  <%= link_to "Show this fornecedores endereco", fornecedor_fornecedores_endereco_path(@fornecedor, @fornecedores_endereco) %> |
  <%= link_to "Back to fornecedores endereco", fornecedor_fornecedores_enderecos_path(@fornecedor) %>
</div>

app/views/fornecedores_enderecos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Endereços do fornecedor: <%= @fornecedor.nome %></h1>

<div id="fornecedores_enderecos">
  <% @fornecedores_enderecos.each do |fornecedores_endereco| %>
    <%= render fornecedores_endereco %>
    <p>
      <%= link_to "Show this fornecedores endereco", fornecedor_fornecedores_endereco_path(@fornecedor, fornecedores_endereco) %>
    </p>
  <% end %>
</div>

<%= link_to "New fornecedores endereco", new_fornecedor_fornecedores_endereco_path(@fornecedor) %>

app/views/fornecedores_enderecos/new.html.erb
<h1>New fornecedores endereco</h1>

<%= render "form", fornecedores_endereco: @fornecedores_endereco %>

<br>

<div>
  <%= link_to "Back to fornecedores endereco", fornecedor_fornecedores_enderecos_path(@fornecedor) %>
</div>

app/views/fornecedores_enderecos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @fornecedores_endereco %>

<div>
  <%= link_to "Edit this fornecedores endereco", edit_fornecedor_fornecedores_endereco_path(@fornecedor, @fornecedores_endereco) %> |
  <%= link_to "Back to fornecedores endereco", fornecedor_fornecedores_enderecos_path(@fornecedor) %>

  <%= button_to "Destroy this fornecedores endereco", fornecedor_fornecedores_endereco_path(@fornecedor, @fornecedores_endereco), method: :delete %>
</div>